-- 코드를 입력하세요
-- SELECT b.BOOK_ID AS BOOK_ID, a.AUTHOR_NAME AS AUTHOR_NAME, b.PUBLISHED_DATE AS PUBLISHED_DATE
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK b
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;